# 指定语言为node_js, nodejs版本stable
language: node_js
node_js: stable

# 指定构建的分支
branches:
  only:
    - code

# 制定node_modules缓存
cache:
  directories:
    - node_modules

# 构建之前安装hexo-cli
before_install:
  - npm install -g hexo-cli

# 安装依赖
install:
 - npm install

# 执行脚本
script:
  - hexo clean
  - hexo generate

# 上面的脚本执行成功之后执行deploy
after_success:
  - git init
  - git config --global user.name "huguanghui"
  - git config --global user.email "522146829@qq.com"
  # 替换同目录下_config.yml文件中的GH_TOKEN字符串为travis后台配置的GH_TOKEN
  - sed -i "s/GH_TOKEN/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy